- yum:
    state: latest
    name:
      - ipsilon-client

- copy: src=ipsilon-pwd-file dest=/tmp/ipsilon-pwd-file

- command: /usr/bin/ipsilon-client-install --saml-idp-url https://ipa.vagrant.develop/idp/ --saml-sp-name "Test Client1" --admin-user admin --admin-password /tmp/ipsilon-pwd-file --saml-auth /
