- hosts: "samba-server:idm-server:client"
  become: true
  tasks:
    # - debug: msg="{{ansible_hostname}}"
    # - debug: msg="{{ansible_fqdn}}"
    # - name: clean loopback address
    #   lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1[\s]+{{ansible_hostname}}' state=absent
    - include: tasks/common.yml

- hosts: samba-server
  become: true
  tasks:
    - include: tasks/samba-server.yml

- hosts: idm-server
  become: true
  tasks:
    - include: tasks/idm-server.yml
    - include: tasks/ipsilon-server.yml

- hosts: client
  become: true
  tasks:
    - include: tasks/idm-client.yml
    - include: tasks/ipsilon-client.yml
